# Numpy (Part-2)

In [1]:
import numpy as np

In [2]:
#Empty Array
empty = np.empty((2,3))
empty

array([[3.47739925e-081, 3.41865071e-032, 1.10575385e-046],
       [1.87027637e-051, 7.49118145e-067, 3.24042835e-319]])

In [10]:
empty = np.empty((2,3))
print(empty)
print("___________________________________________________")
print(empty[0])

[[3.47739925e-081 3.41865071e-032 1.10575385e-046]
 [1.87027637e-051 7.49118145e-067 3.24042835e-319]]
___________________________________________________
[3.47739925e-81 3.41865071e-32 1.10575385e-46]


In [20]:
#Arange function
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
#Reshape
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
#Even number
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [18]:
#Odd Numbers
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [19]:
#Specific difference between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [24]:
#linspace function
lin = np.linspace(0,10,num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
lin = np.linspace(0,-10,num=5)
lin

array([  0. ,  -2.5,  -5. ,  -7.5, -10. ])

In [26]:
#Define the data type of array
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [27]:
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

# What is the difference between int32 & 64?

**int32:**
- A 32-bit signed integer type
- Occupies 4 bytes (32 bits) of memory
- Range: -2,147,483,648 to 2,147,483,647

**int64**
- A 64-bit signed integer type
- Occupies 8 bytes (64 bits) of memory
- Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807

### Key differences:

- Size: int64 is twice as large as int32, occupying 8 bytes of memory compared to 4 bytes.
- Range: int64 has a much larger range than int32, making it suitable for representing very large or very small integers.

In [28]:
#Sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [30]:
#Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
#Concatenation on specific axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [37]:
#Create a 3D array
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
a.ndim

3

In [39]:
a.size

8

In [40]:
len(a)

2

In [41]:
a.dtype

dtype('int32')

In [42]:
a.shape

(2, 2, 2)

In [44]:
a.reshape(4,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]]])

In [45]:
#array conversion
#Create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
#Convert into 2D Array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7]])

In [50]:
c = a[:, np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

# Indexing and slicing

In [51]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a[1:7]

array([2, 3, 4, 5, 6, 7])

In [60]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
b[b > 11]

array([12])

In [70]:
#Filter even numbers
b[b % 2 == 0] 

array([ 2,  4,  6,  8, 10, 12])

In [71]:
 #Filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [73]:
#Use two conditions
b[(b > 2) & (b % 2 == 0)]

array([ 4,  6,  8, 10, 12])

In [74]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])